export const personActionTypes={
    FETCH_PERSON_TV_MOVIE_REQUEST: 'FETCH_PERSON_TV_MOVIE_REQUEST',
    FETCH_PERSON_TV_MOVIE_SUCCESS: 'FETCH_PERSON_TV_MOVIE_SUCCESS',
    FETCH_PERSON_TV_MOVIES_FAILURE: 'FETCH_PERSON_TV_MOVIES_FAILURE',
    
}